Repository DeveloperAcademy-POSTECH/MacC_WalkingAssistant_iOS, pull requests merged in 2022-11, with the labels that each got.

#23 [Docs] # 22 Conventions.md 내 목차 추가
  Conventions.md
Labels: documentation

#35 [Docs] #34 Conventions.md 내 목차 수정
  Conventions.md
Labels: documentation

#39 [Feat] #38 앱 아이콘 파일 업데이트
  Oculo/Assets.xcassets/AppIcon.appiconset/OculoAppIcon.png
  Oculo/Assets.xcassets/AppIcon.appiconset/Oculo_logo.png
Labels: chore

#46 [Fix] #44 터치 영역 버그 수정
  Oculo/MainViewController.swift
Labels: bug, enhancement

#45 [Fix] #44 ViewController -> MainViewController
  Oculo/MainViewController.swift
Labels: bug

#48 [Feat] #47 ObjectRecognitionViewController 추가
  Oculo/MainViewController.swift
  Oculo/ObjectRecognitionViewController.swift
Labels: enhancement

#49 [Design] #33 기본 Dark모드로 적용
  Oculo.xcodeproj/project.pbxproj
  Oculo/MainViewController.swift
  Oculo/SettingViewController.swift
Labels: chore

#52 [Feat] #50 SoundManger 추가
  Oculo/SoundManager.swift
  Oculo/sources/defaultBeep.mp3
Labels: chore

#56 [Refactor] MainView 버튼 구조 Frame -> Constrains 전환 #54
  Oculo/MainViewController.swift
Labels: refactor

#58 [Add] TextReaderViewController추가 #57
  Oculo.xcodeproj/project.pbxproj
  Oculo/TextReaderViewController.swift
Labels: enhancement

#64 [Chore] 빈 칸(whitespace) 제거 및 주석 맞춤법, 띄어쓰기 수정
  Oculo.xcodeproj/project.pbxproj
  Oculo.xcodeproj/project.xcworkspace/xcuserdata/raymond.xcuserdatad/UserInterfaceState.xcuserstate
  Oculo/AppDelegate.swift
  Oculo/HealthkitManager.swift
  Oculo/MainViewController.swift
  Oculo/ObjectRecognizer/BoundingBoxDisplayView.swift
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
  Oculo/SettingViewController.swift
  Oculo/SoundManager.swift
  Oculo/Sources/defaultBeep.mp3
  Oculo/TextReaderViewController.swift
  Oculo/Utilities/AreaRateChangeTracker.swift
  Oculo/Utilities/MeasurementsTool.swift
  Oculo/Utilities/UIImage_CVPixelBufferTool.swift
  Oculo/Utilities/VideoCaptureTool.swift
Labels: chore

#69 [Feat] #68 Environment Reader 기능 추가 (문 인식만)
  Oculo.xcodeproj/project.pbxproj
  Oculo/Assets.scnassets/CameraSetup.scn
  Oculo/Assets.scnassets/wireframe_shader.metal
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
  Oculo/EnvironmentReader/Plane.swift
  Oculo/EnvironmentReader/Utilities.swift
  Oculo/MainViewController.swift
Labels: enhancement

#72 [Fix] #70 긴글자 읽기 관련 이슈 해결
  Oculo/TextReaderViewController.swift
Labels: bug

#73 [Feat] #67 Localizing 언어 변환
  Oculo.xcodeproj/project.pbxproj
  Oculo/MainViewController.swift
  Oculo/SettingViewController.swift
  Oculo/Utilities/StringExtension.swift
  Oculo/Utilities/en.lproj/Localizable.strings
  Oculo/Utilities/ko.lproj/Localizable.strings
Labels: enhancement

#75 [Fix] #71 화면 회전시 UI 깨짐 현상
  Oculo/AppDelegate.swift
Labels: bug

#77 [Design] 다양한 버전 AppIcon 추가
  Oculo.xcodeproj/project.pbxproj
  Oculo/Assets.xcassets/AppIcon.appiconset/1024.png
  Oculo/Assets.xcassets/AppIcon.appiconset/114.png
  Oculo/Assets.xcassets/AppIcon.appiconset/120.png
  Oculo/Assets.xcassets/AppIcon.appiconset/180.png
  Oculo/Assets.xcassets/AppIcon.appiconset/29.png
  Oculo/Assets.xcassets/AppIcon.appiconset/40.png
  Oculo/Assets.xcassets/AppIcon.appiconset/57.png
  Oculo/Assets.xcassets/AppIcon.appiconset/58.png
  Oculo/Assets.xcassets/AppIcon.appiconset/60.png
  Oculo/Assets.xcassets/AppIcon.appiconset/80.png
  Oculo/Assets.xcassets/AppIcon.appiconset/87.png
  Oculo/Assets.xcassets/AppIcon.appiconset/Contents.json
  Oculo/Assets.xcassets/AppIcon.appiconset/OculoAppIcon.png
  Oculo/Assets.xcassets/appstore.imageset/Contents.json
  Oculo/Assets.xcassets/appstore.imageset/appstore.png
Labels: design

#79 [Refactor] #78 Deprecated 함수 변경
  Oculo/EnvironmentReader/Plane.swift
  Oculo/EnvironmentReader/Utilities.swift
Labels: refactor

#81 [Refactor] #76 기능 합치기 -> TTS 기능 별도로 묶기
  Oculo.xcodeproj/project.pbxproj
  Oculo/TextReaderViewController.swift
  Oculo/Utilities/TTSTool.swift
Labels: refactor

#83 [Feat] #63 #82 ARSession 변경 및 LiDAR 추가
  Oculo.xcodeproj/project.pbxproj
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
  Oculo/Utilities/VideoCaptureTool.swift
Labels: enhancement, refactor

#90 [Docs] 라이센스 변경
  LICENSE
Labels: documentation

#89 [Docs] README 업데이트
  README.md
Labels: documentation

#87 [Chore] 깃 이그노어 파일 업데이트
  .gitignore
Labels: chore

#88 [Chore] 소스코드 출처 표기
  Oculo.xcodeproj/project.pbxproj
  Oculo.xcodeproj/project.xcworkspace/xcuserdata/raymond.xcuserdatad/UserInterfaceState.xcuserstate
  Oculo/HealthkitManager.swift
  Oculo/KalmanFilter/DoubleExtension.swift
  Oculo/KalmanFilter/KalmanFilter.swift
  Oculo/KalmanFilter/KalmanFilterType.swift
  Oculo/KalmanFilter/KalmanMatrix.swift
  Oculo/ObjectRecognizer/BoundingBoxDisplayView.swift
  Oculo/ObjectRecognizer/LabelsTableViewCell.swift
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
  Oculo/SoundManager.swift
  Oculo/Utilities/AreaRateChangeTracker.swift
  Oculo/Utilities/TTSTool.swift
Labels: documentation

#85 [Feat] 칼만 필터 추가
  Oculo.xcodeproj/project.pbxproj
  Oculo.xcodeproj/project.xcworkspace/xcuserdata/raymond.xcuserdatad/UserInterfaceState.xcuserstate
  Oculo/KalmanFilter/DoubleExtension.swift
  Oculo/KalmanFilter/KalmanFilter.swift
  Oculo/KalmanFilter/KalmanFilterType.swift
  Oculo/KalmanFilter/KalmanMatrix.swift
  Oculo/SoundManager.swift
Labels: enhancement

#91 [Chore] #63 #82 whitespace 제거 및 주석, 인덴트 수정
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
Labels: chore

#92 [Fix] Cocoapods 적용 취소
  .gitignore
  Oculo.xcodeproj/project.xcworkspace/xcuserdata/raymond.xcuserdatad/UserInterfaceState.xcuserstate
Labels: bug

#94 [Fix] 코코아팟 드디어 제거
  Oculo.xcodeproj/project.pbxproj
  Oculo.xcodeproj/project.xcworkspace/xcuserdata/raymond.xcuserdatad/UserInterfaceState.xcuserstate
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
Labels: bug

#100 [Feat] #95 Tts, VoiceOver 관련 추가 설정
  Oculo/TextReaderViewController.swift
  Oculo/Utilities/TTSTool.swift
Labels: enhancement

#101 [Feat] SORT 알고리즘 스켈레톤 코드 작성: 100%
  Oculo.xcodeproj/project.pbxproj
  Oculo.xcodeproj/project.xcworkspace/xcuserdata/raymond.xcuserdatad/UserInterfaceState.xcuserstate
  Oculo/DeepSORT/ObjectTracker.swift
  Oculo/KalmanFilter/DoubleExtension.swift
  Oculo/KalmanFilter/KalmanFilter.swift
  Oculo/KalmanFilter/KalmanFilterType.swift
  Oculo/KalmanFilter/KalmanMatrix.swift
Labels: enhancement

#102 [Fix] 빌드 안되는 에러 해결
  Oculo.xcodeproj/project.pbxproj
  Oculo/DeepSORT/ObjectTracker.swift
Labels: bug

#107 [Feat] AR 버전 문과 카메라의 거리 측정 및 표시, AR기능 사용 중 문제 발생시 말하기 기능
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
  Oculo/EnvironmentReader/Plane.swift
Labels: enhancement

#109 [Fix] #108 SoundManager블루투스이어폰 연결 또는 끊김시 발생하는 오류해결, 구조개선
  Oculo/SoundManager.swift
Labels: refactor

#110 [Feat] #106 ARSession Image capture 리팩토링
  Oculo.xcodeproj/project.pbxproj
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
Labels: refactor

#111 [Chore] whitespace 및 typo 수정
  Conventions.md
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
Labels: chore

#113 [Feat] HealthKitManager 연동, TTS 적용
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
  Oculo/EnvironmentReader/Plane.swift
  Oculo/HealthkitManager.swift
  Oculo/MainViewController.swift
Labels: enhancement

#116 Refactor/tts tools merge to sound manager
  Oculo.xcodeproj/project.pbxproj
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
  Oculo/EnvironmentReader/Plane.swift
  Oculo/MainViewController.swift
  Oculo/TextReaderViewController.swift
  Oculo/Utilities/HealthkitManager.swift
  Oculo/Utilities/SoundManager.swift
  Oculo/Utilities/TTSTool.swift
Labels: refactor

#120 [Feat] 복수의 문 인식 방법 개선, 인식 초기화 버튼 배치
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
Labels: enhancement

#123 [Refactor] Environment Reader 관련 View 배치 함수 정리, 오타 수정
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
  Oculo/TextReaderViewController.swift
  Oculo/Utilities/ko.lproj/Localizable.strings
Labels: refactor

#125 [Feat] 문 인식에 대한 안내 멘트 추가 및 변경
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
Labels: enhancement

#127 [Feat] #55 Custom rotor 각 뷰에서 적용시켰습니다.
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
  Oculo/MainViewController.swift
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
  Oculo/TextReaderViewController.swift
Labels: enhancement

#129 [Fix] #128 버튼 제목 제거
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
  Oculo/TextReaderViewController.swift
Labels: bug

#133 [Feat] 가장 가까이 있는 물체의 좌표와 라벨을 synthesizer 로 읽어주는 기능입니다. #131
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
Labels: enhancement

#132 [Feat] #130 설정 화면, 버튼을 라이선스에 맞게 변경
  Oculo/MainViewController.swift
  Oculo/SettingViewController.swift
Labels: enhancement

#134 Fix/synthesizer playback problem
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
  Oculo/Utilities/SoundManager.swift
Labels: enhancement
