Repository DeveloperAcademy-POSTECH/MacC_WalkingAssistant_iOS, pull requests merged in 2022-12, with the labels that each got.

#139 Design/Main Button Color
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
  Oculo/MainViewController.swift
  Oculo/TextReaderViewController.swift
  Oculo/Utilities/StringExtension.swift
  Oculo/Utilities/en.lproj/Localizable.strings
  Oculo/Utilities/ko.lproj/Localizable.strings
Labels: bug, design

#141 [Feat] #140 근접센서 동작 ObjectRecognizer로 변경, 근접센서 관련 음성안내 추가, TTS 속도 조절
  Oculo/MainViewController.swift
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
  Oculo/Utilities/SoundManager.swift
Labels: enhancement

#143 [Feat] LiDAR 없는 휴대폰의 기능사용 불가 알림 #142
  Oculo/MainViewController.swift
  Oculo/Utilities/StringExtension.swift
Labels: enhancement

#144 [Fix] 알림창 나오지 않는 오류 수정
  Oculo/MainViewController.swift
Labels: bug

#146 [Fix] 근접센서 관련 부분 제거
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
Labels: bug

#147 [Docs] 개인정보처리방침
  Oculo/Privacy_Policy.html
Labels: documentation

#148 [Fix] HealthKit 제거
  Oculo.xcodeproj/project.pbxproj
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
  Oculo/EnvironmentReader/Plane.swift
  Oculo/Info.plist
  Oculo/MainViewController.swift
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
  Oculo/Oculo.entitlements
  Oculo/Utilities/HealthkitManager.swift
Labels: bug

#150 Feat/setting view and control tts speed #140
  Oculo.xcodeproj/project.pbxproj
  Oculo/LicenseVIewController.swift
  Oculo/MainViewController.swift
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
  Oculo/SettingViewController.swift
  Oculo/Utilities/SoundManager.swift
  Oculo/Utilities/StringExtension.swift
  Oculo/Utilities/en.lproj/Localizable.strings
  Oculo/Utilities/ko.lproj/Localizable.strings
Labels: enhancement

#153 [Fix] VoiceOver 충돌 해결
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
  Oculo/Utilities/SoundManager.swift
Labels: bug

#159 Delete Privacy_Policy.html
  Oculo/Privacy_Policy.html
Labels: del

#161 [Feature] 스크린 자동잠금 방지
  Oculo.xcodeproj/project.pbxproj
  Oculo/SceneDelegate.swift
Labels: enhancement

#160 [Chore] 칼만 필터 연산 과정 설명 추가
  Oculo.xcodeproj/project.xcworkspace/xcuserdata/raymond.xcuserdatad/UserInterfaceState.xcuserstate
  Oculo/DeepSORT/KalmanFilter/KalmanFilter.swift
Labels: chore

#162 [Chore] 주석 및 whitespace 정리
  Oculo.xcodeproj/project.xcworkspace/xcuserdata/raymond.xcuserdatad/UserInterfaceState.xcuserstate
  Oculo/DeepSORT/KalmanFilter/KalmanMatrix.swift
  Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
  Oculo/EnvironmentReader/Plane.swift
  Oculo/LicenseVIewController.swift
  Oculo/MainViewController.swift
  Oculo/ObjectRecognizer/BoundingBoxDisplayView.swift
  Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
  Oculo/SettingViewController.swift
  Oculo/TextReaderViewController.swift
  Oculo/Utilities/SoundManager.swift
  Oculo/Utilities/StringExtension.swift
  Oculo/Utilities/UIImage_CVPixelBufferTool.swift
Labels: chore

#165 Update README.md
  README.md
Labels: chore
