Repository DeveloperAcademy-POSTECH/MacC_WalkingAssistant_iOS, pull requests merged in 2022-10, with the labels that each got.

#1 Create README.md
  README.md
Labels: documentation

#2 Create .gitignore
  .gitignore
Labels: enhancement

#3 Create .gitattributes
  .gitattributes
Labels: enhancement

#4 Skeleton code
  Oculo.xcodeproj/project.pbxproj
  Oculo.xcodeproj/project.xcworkspace/xcuserdata/raymond.xcuserdatad/UserInterfaceState.xcuserstate
  Oculo/AppDelegate.swift
  Oculo/FunctionCells.swift
  Oculo/MainViewController.swift
  Oculo/SwipingController.swift
Labels: enhancement

#7 Add a toggle button to change UI interchangeably
  Oculo/MainViewController.swift
Labels: enhancement

#9 버튼 모양 수정, 클릭 이벤트 추가
  Oculo/MainViewController.swift
Labels: enhancement

#8 Health kit manager
  Oculo.xcodeproj/project.pbxproj
  Oculo/HealthkitManager.swift
  Oculo/Info.plist
  Oculo/Oculo.entitlements
Labels: enhancement

#11 Readability improvement
  Oculo/AppDelegate.swift
  Oculo/FunctionCells.swift
  Oculo/HealthkitManager.swift
  Oculo/MainViewController.swift
  Oculo/SceneDelegate.swift
  Oculo/SwipingGestureRecognizer.swift
Labels: documentation

#16 UI 플랜 변경으로 코드 수정: 토글 버튼 및 UI 안내 레이블 영역 삭제
  Oculo/AppDelegate.swift
  Oculo/FunctionCells.swift
  Oculo/MainViewController.swift
  Oculo/SwipingGestureRecognizer.swift
Labels: enhancement

#17 근접 센서 추가, 설정 화면 생성
  Oculo.xcodeproj/project.pbxproj
  Oculo/Assets.xcassets/settingViewLogo.imageset/Contents.json
  Oculo/Assets.xcassets/settingViewLogo.imageset/image 1.png
  Oculo/MainViewController.swift
  Oculo/SettingViewController.swift
Labels: enhancement

#18 AppIcon 추가
  .gitignore
  Oculo/Assets.xcassets/AppIcon.appiconset/Contents.json
  Oculo/Assets.xcassets/AppIcon.appiconset/Oculo_logo.png
Labels: documentation, enhancement

#20 [Docs] #21 Conventions.md 업데이트
  Conventions.md
Labels: documentation
